services:
  db:
    image: postgres:17
    container_name: bookingdb
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookingdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: bookingdb
      PGPASSWORD: yourpassword
      PGPORT: "5432"
      PORT: "3520"
    ports:
      - "3520:3520"
    restart: unless-stopped
volumes:
  db_data:
